name: Deploy to heroku

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_compose_file: './docker-compose.yml'
          heroku_apps: '[{"imagename":"server","appname":"server","apptype":"web"},{"imagename":"client","appname":"client","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
